server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: register-rout
              uri: lb://auth-service
              predicates:
                - Path=/registering/**,/auth/**
            - id: user-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**

crypto:
  security:
    jwt:
      secret-key: 4mA5LQm6W9xZ2pR8sV1nB3cD7fG0hJkL9pQ2rT5yU8iO1aS4dF