server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: register-rout
              uri: lb://auth-service
              predicates:
                - Path=/registering/**,/auth/**
            - id: user-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
            - id: email-route
              uri: lb://EMAIL-SERVICE
              predicates:
                - Path=/email/**

crypto:
  security:
    jwt:
      secret-key: ${SECRET_KEY}