### Send POST request with json body
POST http://localhost:8000/registering/register
Content-Type: application/json

{
  "username": "softwareEngineer",
  "email": "daraeialireza76@gmail.com",
  "password": "1234"
}