POST http://localhost:8005/wallet/deposit
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJSRUFEIl0sInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJ1c2VyVVVJRCI6IjAzZmVhMjIyLTM0ODItNDAwMS05NmU2LTZhNzdmMzNlZDNlZCIsInVzZXJJZCI6NDMsImVtYWlsIjoiZGFyYWVpYWxpcmV6YTc2QGdtYWlsLmNvbSIsInN1YiI6InNvZnR3YXJlRW5naW5lZXIiLCJleHAiOjE3ODk4NTU0MzYsImlhdCI6MTc4OTg1NTEzNn0.uDIFBa4OhABtpgYu4j8PdXYEXsZfGd3Fvlrhj_hXj7k
Content-Type: application/json

{
  "asset": "BTC",
  "amount": "0.15"
}